application: liftmomobile
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /maui
  static_dir: maui

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /pages
  static_dir: pages

- url: /img
  static_dir: img

- url: .*
  script: index.html